### ISSUE TITLE
The performance for finding files is poor.

### ISSUE THREAD

**Issue by feixue8421** [DonJayamanne/listFilesVSCode#2]
I got a working folder with about 20,000 files. Then, the performance issue occurred when finding files, i.e. finding ".cpp" files. There are symbolic links in my folder and I do not know whether it matters. The GUI was blocking for a while. Hope this can be fixed soon.

**Comment by DonJayamanne** [comment]
This extension is obsolete, you might want to use the native find file feature in vscode

**Comment by feixue8421** [comment]
Yes, you are right. Thanks a lot for your quick response!
